In [ ]:
## Karan Sah_2329860
4MM013
Python Assessment 2
Description
This assessment will allow you to demonstrate your Python programming abilities by producing solutions to the following questions. For each question you will need to produce evidence of the code you have created, ideally in an IDE, and also proof of the valid output generated by running your code. The code created should also satisfy the following requirements;

●	Use suitable variable and function names which, where possible, betray the data type or function’s operation / role.
●	Use comments to explain the primary operations, role, or behaviour of your code.
●	Contain a “##” title with a description, your name and student number at the start of the program.

The total marks for the assessment is 15.
 
Question 1

Create a python script that will prompt the user for 9 values, checking that they are all valid numbers, and populate those given values into a 3x3 Matrix called A.

The program should present the created matrix , the determinant of the matrix and, if possible, the inverse of the matrix.

The program should also present the results of the matrix operations A*A and A*A*A Finally the program should print the number of values in the matrix that >= 10
You will need to evidence the outputs, as well as the error handling of any invalid values when the user attempts to input them in the matrix.


In [11]:
##Question_1_Answer Karan Sah 2329860
import numpy as np

# User input valildation and defining a function for it 
def validate_input(prompt):
    while True:
        try:
            value = float(input(prompt))
            return value
        except ValueError:
            print("Invalid input. Please enter a valid number.")

# Ask user for 9 values to put in 3*3 martix A. 
A = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        A[i][j] = validate_input(f"Enter value for A[{i+1}][{j+1}]: ")

# Print the created matrix A
print("Matrix A:\n", A)

# Calculate the determinant of A and print it
det = np.linalg.det(A)
print("|A| =", det)

# Calculate the inverse of A, if possible, and print it
try:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
except np.linalg.LinAlgError:
    print("Inverse of A does not exist.")

# Perform matrix operations A*A and A*A*A, and print the results
print("A*A:\n", np.matmul(A, A))
print("A*A*A:\n", np.matmul(np.matmul(A, A), A))

# Count the number of values in A that are >= 10, and print the count
count = 0
for i in range(3):
    for j in range(3):
        if A[i][j] >= 10:
            count += 1
print("Number of values in A that are >= 10:", count)


Enter value for A[1][1]: 2
Enter value for A[1][2]: 4
Enter value for A[1][3]: 6
Enter value for A[2][1]: 8
Enter value for A[2][2]: 10
Enter value for A[2][3]: 12
Enter value for A[3][1]: 14
Enter value for A[3][2]: 16
Enter value for A[3][3]: 17
Matrix A:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 17.]]
|A| = 11.999999999999995
Inverse of A:
 [[-1.83333333  2.33333333 -1.        ]
 [ 2.66666667 -4.16666667  2.        ]
 [-1.          2.         -1.        ]]
A*A:
 [[120. 144. 162.]
 [264. 324. 372.]
 [394. 488. 565.]]
A*A*A:
 [[ 3660.  4512.  5202.]
 [ 8328. 10248. 11796.]
 [12602. 15496. 17825.]]
Number of values in A that are >= 10: 5


Write and test a Python function, that makes use of numpy, to return the sum of the elements on the main diagonal (upper left to lower right) of a square matrix. In linear algebra, this value is called the trace of the matrix.

For example, with a matrix represented as a list of lists eg. [[9, 8, 7], [6, 5, 4], [3, 2, 1]], your function
should return (9 + 5 + 1) = “15”

Your Python function solution should work for any sized square matrix passed to it. Demonstrate that this is the case with 3x3, 4x4, and 6x6 matrix examples.
 


In [12]:
##Question_2_Answer Karan Sah 2329860
import numpy as np

def matrix_trace(matrix):
    """
    This function takes a square matrix represented as a list of lists and returns the sum of the elements on the
    main diagonal (upper left to lower right) of the matrix, which is known as the trace of the matrix.

    :param matrix: list of lists representing the square matrix
    :return: sum of elements on the main diagonal of the matrix
    """

    # convert the matrix to a numpy array
    matrix_np = np.array(matrix)

    # extract the diagonal elements of the matrix as a 1D array
    diagonal = np.diagonal(matrix_np)

    # compute the sum of the diagonal elements
    trace = np.sum(diagonal)

    return trace
matrix_3x3 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
trace_3x3 = matrix_trace(matrix_3x3)
print("Trace of 3x3 matrix: ", trace_3x3)

matrix_4x4 = [[16, 15, 14, 13], [12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]]
trace_4x4 = matrix_trace(matrix_4x4)
print("Trace of 4x4 matrix: ", trace_4x4)

matrix_6x6 = [[36, 35, 34, 33, 32, 31], [30, 29, 28, 27, 26, 25], [24, 23, 22, 21, 20, 19], [18, 17, 16, 15, 14, 13], [12, 11, 10, 9, 8, 7], [6, 5, 4, 3, 2, 1]]
trace_6x6 = matrix_trace(matrix_6x6)
print("Trace of 6x6 matrix: ", trace_6x6)

  


Trace of 3x3 matrix:  15
Trace of 4x4 matrix:  34
Trace of 6x6 matrix:  111


Ackermann's function (A) is defined as:


A(m,n):
n+1, if m=0
A(m-1,1), if m>0 and n=0
A(m-1,A(m,n-1)), if m>0 and n> 0


Write a recursive Python function to implement Ackermann's function. How many recursive calls will be required to evaluate A(2,3)?


In [13]:
##Question_3_Answer Karan Sah 2329860
def A(m, n, count=1):
    # Print the current call and the count
    print(f"A({m}, {n}), call {count}")
    
    # Base case 1: if m is 0, return n+1
    if m == 0:
        return n + 1, count
    
    # Base case 2: if n is 0, call A(m-1, 1)
    elif n == 0:
        return A(m - 1, 1, count + 1)
    
    # Recursive case: call A(m-1, A(m, n-1))
    else:
        a, count = A(m, n - 1, count + 1)
        return A(m - 1, a, count + 1)

# Test the function with m=2, n=3
result, count = A(2, 3)
print("A(2, 3) = ", result)
print("Number of function calls: ", count)




A(2, 3), call 1
A(2, 2), call 2
A(2, 1), call 3
A(2, 0), call 4
A(1, 1), call 5
A(1, 0), call 6
A(0, 1), call 7
A(0, 2), call 8
A(1, 3), call 9
A(1, 2), call 10
A(1, 1), call 11
A(1, 0), call 12
A(0, 1), call 13
A(0, 2), call 14
A(0, 3), call 15
A(0, 4), call 16
A(1, 5), call 17
A(1, 4), call 18
A(1, 3), call 19
A(1, 2), call 20
A(1, 1), call 21
A(1, 0), call 22
A(0, 1), call 23
A(0, 2), call 24
A(0, 3), call 25
A(0, 4), call 26
A(0, 5), call 27
A(0, 6), call 28
A(1, 7), call 29
A(1, 6), call 30
A(1, 5), call 31
A(1, 4), call 32
A(1, 3), call 33
A(1, 2), call 34
A(1, 1), call 35
A(1, 0), call 36
A(0, 1), call 37
A(0, 2), call 38
A(0, 3), call 39
A(0, 4), call 40
A(0, 5), call 41
A(0, 6), call 42
A(0, 7), call 43
A(0, 8), call 44
A(2, 3) =  9
Number of function calls:  44
